language: go

env:
  - GO111MODULE=on

services:
  - docker

before_install:
  - docker pull centrifugo/centrifugo
  - docker run -d -p 8000:8000 centrifugo/centrifugo centrifugo --client_insecure
go:
  - "1.14.x"
  - "1.13.x"
  - "tip"

script: go test -race -v
